### ISSUE TITLE
Feature Request: Add Paillier Encryption

### ISSUE THREAD

**Issue by Athishpranav2003** [xavierleroy/cryptokit#38]
Extend support for Homomorphic Encryption Algorithm - Paillier Encryption. This could be useful since this scheme is widely used in E-voting related work.

**Comment by Athishpranav2003** [comment]
@xavierleroy I am raising this issue and willing to work on it as well once you confirm. Incase if its not appropriate please let me know asap

**Comment by xavierleroy** [comment]
Thanks for pointing Paillier encryption out, I didn't know about it.  For reference: https://en.wikipedia.org/wiki/Paillier_cryptosystem

As you noticed, Cryptokit is very poor in the public-key cryptography department, in part because it doesn't implement elliptic curves.  Paillier is just modular arithmetic, and would add new capabilities (homomorphic encryption), so I'm in favor of having it in Cryptokit eventually.

Feel free to try to implement it and to submit a pull request.

**Comment by Athishpranav2003** [comment]
@xavierleroy thanks for the reply. I have already added an implementation in mirage-crypto so I guess adding it here won't be a problem

**Comment by Athishpranav2003** [comment]
https://github.com/Athishpranav2003/mirage-crypto

I added the implementation and tested it here. Will go ahead and add it to cryptokit as well
